// Auto-generated by CMake — do not edit. See root CMakeLists.txt.
#ifndef CHIAKI_VERSION_H
#define CHIAKI_VERSION_H

#define CHIAKI_VERSION_MAJOR 2
#define CHIAKI_VERSION_MINOR 10
#define CHIAKI_VERSION_PATCH 19
#define CHIAKI_VERSION "2.10.19"

#endif // CHIAKI_VERSION_H
